var data =[
    {
      "title": "Benjamin Harrison Statue",
      "url": "img_prints/benHarrisonStatue2.jpg",
      "url2": "img_prints/iuPlaque.jpg",
      "location": "IUPUI",
      "print_material": "Resin",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "print",
      "collaborator":"AVL, Benjamin Harrison Presidential Site (BHPS), University Library's Center for Digital Scholarship",
      "print_date":"Fall 2016",
      "printer_type":"Formlab 2+",
      "print_scale":"No",
      "print_color":"Black",
      "description": "Statue of president Benjamin Harrison that is approximately 3 ft. tall, and made of bronze. From the Benjamin Harrison Presidential Sitecollection. Object digitized using 3D scanning technologies as a means to digital preservation, and 3D printed to showcase results."
  },
    {
      "title": "IU Medical Plaque",
      "url": "img_objects/iuPlaque.jpg",
      "url2": "img_objects/iuPlaque.jpg",
      "location": "IUPUI",
      "print_material": "Rigid Opaque Photopolymer",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "object",
      "collaborator":"AVL, Ruth Lilly Medical Library",
      "print_date":"Fall 2016",
      "printer_type":"Object30",
      "print_scale":"no",
      "print_color":"VeroBlue",
      "description": "Historical artifact from Ruth Lilly Medical Library collection.  Wooden gavel presented to the Medical College of Indiana (Class of 1904) by one of its members."
  }, {
      "title": "IU Medical Plaque",
      "url": "img_prints/iuPlaque2.jpg",
    "url2": "img_prints/iuPlaque2.jpg",
      "location": "IUPUI",
      "print_material": "Rigid Opaque Photopolymer",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "print",
      "collaborator":"AVL, Ruth Lilly Medical Library",
      "print_date":"Fall 2016",
      "printer_type":"Object30",
      "print_scale":"No",
      "print_color":"VeroBlue",
      "description": "Historical artifact from Ruth Lilly Medical Library collection.  Wooden gavel presented to the Medical College of Indiana (Class of 1904) by one of its members."
  }, {
      "title": "Mastodon Jaw Bone Fossil",
      "url": "img_prints/jawbonefossil.jpg",
    "url2": "img_prints/jawbonefossil.jpg",
      "location": "IUB",
      "print_material": "PLA Plastic Filament",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "print",
      "collaborator":"AVL, Center for Biological Research Collections",
      "print_date":"Fall 2016",
      "printer_type":"Ultimaker",
      "print_scale":"No",
      "print_color":"White",
      "description": "Fossil from Indiana Geological Survey. Original artifact is over 3 ft. in length, and fragile. It was 3D scanned as a way to digital preserve it, then 3D printed to allow further study and analysis, without damaging the original. Object photographed by Barb Hill (Indiana Geological Survey Photographer)."
  }, {
      "title": "Mastodon Jaw Bone Fossil",
      "url": "img_objects/jawbonefossil.jpg",
    "url2": "img_objects/jawbonefossil.jpg",
      "location": "IUB",
      "print_material": "PLA Plastic Filament",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "object",
      "collaborator":"AVL, Center for Biological Research Collections",
      "print_date":"Fall 2016",
      "printer_type":"Ultimaker",
      "print_scale":"No",
      "print_color":"White",
      "description": "Fossil from Indiana Geological Survey. Original artifact is over 3 ft. in length, and fragile. It was 3D scanned as a way to digital preserve it, then 3D printed to allow further study and analysis, without damaging the original. Object photographed by Barb Hill (Indiana Geological Survey Photographer)."
  }, {
      "title": "Clam Fossil",
      "url": "img_objects/clamFossil.jpg",
    "url2": "img_objects/clamFossil.jpg",
      "location": "IUB",
      "print_material": "PLA Plastic Filament",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "print",
      "collaborator":"AVL, Center for Biological Research Collections",
      "print_date":"Fall 2016",
      "printer_type":"Ultimaker",
      "print_scale":"Yes",
      "print_color":"Pearl White",
      "description": "Fossil from Indiana University Paleontology Collection. Approximately 80 million year old clam fossil from the Inoceramus genus.  It was 3D scanned as a way to digital preserve it, then 3D printed to allow further study and analysis, without damaging the original. Object photographed by Gary Motz (Department of Geological Sciences)."
  }
  , {
      "title": "Clam Fossil",
      "url": "img_prints/clamFossil.jpg",
    "url2": "img_prints/clamFossil.jpg",
      "location": "IUB",
      "print_material": "PLA Plastic Filament",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "object",
      "collaborator":"AVL, Center for Biological Research Collections",
      "print_date":"Fall 2016",
      "printer_type":"Ultimaker",
      "print_scale":"Yes",
      "print_color":"Pearl White",
      "description": "Fossil from Indiana University Paleontology Collection. Approximately 80 million year old clam fossil from the Inoceramus genus.  It was 3D scanned as a way to digital preserve it, then 3D printed to allow further study and analysis, without damaging the original. Object photographed by Gary Motz (Department of Geological Sciences)."
  }, {
      "title": "Doctor Bust",
      "url": "img_prints/doctorBust.jpg",
    "url2": "img_prints/doctorBust.jpg",
      "location": "IUPUI",
      "print_material": "PLA Plastic Filament",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "print",
      "collaborator":"AVL, Ruth Lilly Medical Library",
      "print_date":"Fall 2016",
      "printer_type":"Ultimaker",
      "print_scale":"No",
      "print_color":"Metallic Grey",
      "description": "Item from Ruth Lilly Medical Library collection. Stone statue bust of former IU dcotor. Object digitized, then 3D printed to showcase results."
  }, {
      "title": "Doctor Bust",
      "url": "img_objects/doctorBust.jpg",
    "url2": "img_objects/doctorBust.jpg",
      "location": "IUPUI",
      "print_material": "PLA Plastic Filament",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "object",
      "collaborator":"AVL, Ruth Lilly Medical Library",
      "print_date":"Fall 2016",
      "printer_type":"Makerbot",
      "print_scale":"",
      "print_color":"",
      "description": "Item from Ruth Lilly Medical Library collection. Stone statue bust of former IU dcotor. Object digitized, then 3D printed to showcase results."
  }, {
      "title": "OB Forceps",
      "url": "img_objects/obForceps.jpg",
    "url2": "img_objects/obForceps.jpg",
      "location": "IUPUI",
      "print_material": "Rigid Opaque Photopolymer",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "object",
      "collaborator":"AVL, Ruth Lilly Medical Library",
      "print_date":"Fall 2016",
      "printer_type":"object30",
      "print_scale":"No",
      "print_color":"Vero Blue",
      "description": "From Ruth Lilly Medical Library collection. Both made of metal, and fit together to allow an open / close motion. Original objects digitized, then 3D printed to simulate functionality."
  }, {
      "title": "OB Forceps",
      "url": "img_prints/obForceps.jpg",
    "url2": "img_prints/obForceps.jpg",
      "location": "IUPUI",
      "print_material": "Rigid Opaque Photopolymer",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "print",
      "collaborator":"AVL, Ruth Lilly Medical Library",
      "print_date":"Fall 2016",
      "printer_type":"Object30",
      "print_scale":"No",
      "print_color":"VeroBlue",
      "description": "From Ruth Lilly Medical Library collection. Both made of metal, and fit together to allow an open / close motion. Original objects digitized, then 3D printed to simulate functionality."
  }, {
      "title": "Barber's Bleeder Bowl",
      "url": "img_objects/barberBleederBowl.jpg",
    "url2": "img_objects/barberBleederBowl.jpg",
      "location": "IUPUI",
      "print_material": "Sandstone",
      "print_service": "Shapeways",
      "object_type": "object",
      "collaborator":"AVL, Ruth Lilly Medical Library",
      "print_date":"Fall 2016",
      "printer_type":"Full-Color Sandstone Printer",
      "print_scale":"No",
      "print_color":"Texture Map",
      "description": "From Leo J. McCarthey personal collection. Glazed ceramic bowl, with tan with black painted rabbit design. Used to collect blood during bloodletting, pre civil-war."
  }, {
      "title": "Barber's Bleeder Bowl",
      "url": "img_prints/barberBleederBowl.jpg",
    "url2": "img_prints/barberBleederBowl.jpg",
      "location": "IUPUI",
      "print_material": "Sandstone",
      "print_service": "Shapeways",
      "object_type": "print",
      "collaborator":"AVL, Ruth Lilly Medical Library",
      "print_date":"Fall 2016",
      "printer_type":"Full-Color Sandstone Printer",
      "print_scale":"No",
      "print_color":"Texture Map",
      "description": "From Leo J. McCarthey personal collection. Glazed ceramic bowl, with tan with black painted rabbit design. Used to collect blood during bloodletting, pre civil-war."
  }, {
      "title": "Elephant",
      "url": "img_objects/elephant2.jpg",
    "url2": "img_objects/elephant2.jpg",
      "location": "IUPUI",
      "print_material": "PLA Wood Filament",
      "print_service": "U.I.T.S Print Lab",
      "object_type": "object",
      "collaborator":"AVL",
      "print_date":"Fall 2016",
      "printer_type":"Makerbot",
      "print_scale":"Yes",
      "print_color":"Brown",
      "description": "Lab demo piece showcasing full scan-to-3D print workflow."
  }, {
      "title": "Elephant",
      "url": "img_prints/elephant.jpg",
    "url2": "img_prints/elephant.jpg",
      "location": "IUPUI",
      "print_material": "PLA Wood Filament",
      "print_service": "U.I.T.S Print Lab",
      "object_type": "object",
      "collaborator":"AVL",
      "print_date":"Fall 2016",
      "printer_type":"Makerbot",
      "print_scale":"Yes",
      "print_color":"Brown",
      "description": "Lab demo piece showcasing full scan-to-3D print workflow."
  }, {
      "title": "CPR Set",
      "url": "img_prints/cprSet2.jpg",
    "url2": "img_prints/cprSet2.jpg",
      "location": "IUPUI",
      "print_material": "PLA Plastic Filament",
      "print_service": "U.I.T.S Print Lab",
      "object_type": "print",
      "collaborator":"AVL, Mechanical Engineering",
      "print_date":"Fall 2016",
      "printer_type":"Makerbot",
      "print_scale":"No",
      "print_color":"Blue",
      "description": "Objects 3D printed to showcase usability for training applications."
  }, {
      "title": "CPR Set",
      "url": "img_objects/cprDummy.jpg",
    "url2": "img_objects/cprDummy.jpg",
      "location": "IUPUI",
      "print_material": "PLA Plastic Filament",
      "print_service": "U.I.T.S Print Lab",
      "object_type": "object",
      "collaborator":"AVL, Mechanical Engineering",
      "print_date":"Fall 2016",
      "printer_type":"Makerbot",
      "print_scale":"No",
      "print_color":"Blue",
      "description": "Objects 3D printed to showcase usability for training applications."
  }, {
      "title": "Clarinet Mouth Piece",
      "url": "img_prints/clarinetMouthPiece2.jpg",
    "url2": "img_prints/clarinetMouthPiece2.jpg",
      "location": "IUB",
      "print_material": "Resin",
      "print_service": "T.I.M.I Print Lab",
      "object_type": "print",
      "collaborator":"AVL, Informatics",
      "print_date":"Summer 2016",
      "printer_type":"FormLab",
      "print_scale":"Yes",
      "print_color":"Clear",
      "description": "Artifact is one of a kind, custom-made clarinet mouth piece. It was digitized with Micro CT scan, and later 3D printed to replicate uniqueness."
  },
    {
      "title": "Finch Bird Skull",
      "url": "img_prints/birdSkull.jpg",
      "url2": "img_prints/birdSkull.jpg",
      "location": "IUB",
      "print_material": "Flexible Plastic",
      "print_service": "Shapeways",
      "object_type": "print",
      "collaborator":"AVL, Medical Sciences",
      "print_date":"Fall 2016",
      "printer_type":"N/A",
      "print_scale":"No",
      "print_color":"White",
      "description": "The results from a project involving the digitization of a finch skull, using Micro CT scan, then 3D printed at an increased scale, to allow for testing of acoustical resonance of internal structure. Object photographed by Gary Motz (Department of Geological Sciences)."
  },
    {
      "title": "Finch Bird Skull",
      "url": "img_objects/birdSkull.jpg",
      "url2": "img_objects/birdSkull.jpg",
      "location": "IUB",
      "print_material": "Flexible Plastic",
      "print_service": "Shapeways",
      "object_type": "object",
      "collaborator":"AVL, Medical Sciences",
      "print_date":"Fall 2016",
      "printer_type":"N/A",
      "print_scale":"No",
      "print_color":"White",
      "description": "The results from a project involving the digitization of a finch skull, using Micro CT scan, then 3D printed at an increased scale, to allow for testing of acoustical resonance of internal structure. Object photographed by Gary Motz (Department of Geological Sciences)."
  },
    {
      "title": "Nuclear Pasta' Model",
      "url": "img_prints/nuclearPasta.jpg",
      "url2": "img_prints/nuclearPasta.jpg",
      "location": "IUB",
      "print_material": "Flexible Plastic",
      "print_service": "Shapeways",
      "object_type": "print",
      "collaborator":"AVL, Physics",
      "print_date":"Fall 2016",
      "printer_type":"N/A",
      "print_scale":"No",
      "print_color":"White",
      "description": "Physics simulation. 3D printed to showcase results, and for further study and analysis."
  }, {
      "title": "Architechtural Model",
      "url": "img_prints/architechturalModel.jpg",
      "url2": "img_prints/architechturalModel.jpg",
      "location": "IUPUI",
      "print_material": "Sandstone",
      "print_service": "",
      "object_type": "print",
      "collaborator":"AVL",
      "print_date":"Fall 2016",
      "printer_type":"N/A",
      "print_scale":"No",
      "print_color":"Texture Map",
      "description": "Architechtural model 3D printed as a color-print demo piece."
  }, {
      "title": "Cancer Cell Model",
      "url": "img_prints/cancerCell2.jpg",
      "url2": "img_prints/cancerCell2.jpg",
      "location": "IUPUI",
      "print_material": "Sandstone",
      "print_service": "AVL McCalla Lab",
      "object_type": "print",
      "collaborator":"AVL",
      "print_date":"Fall 2016",
      "printer_type":"Zcorp 510",
      "print_scale":"No",
      "print_color":"Texture Map",
      "description": "Randy Heiland lead supercomputing simulation. 3D printed to showcase results, and for further study and analysis."
  }
]
